cornerstonejs/cornerstoneWADOImageLoader

- src/imageLoader/wadouri/loadImage.js
`imageCache` stop working when a `promise` is returned instead of a `deferred`
> wadouri: loadDataSetFromPromise should return a deferred instead of a promise

- src/imageLoader/createImage.js
- src/imageLoader/wadors/getPixelData.js
- src/imageLoader/wadors/loadImage.js
- src/imageLoader/wadors/metaData/metaDataProvider.js
- src/imageLoader/wadouri/dataSetCacheManager.js
**Example of a WADO-RS (frame) request:**
curl http://localhost:8042/dicom-web/studies/2.16.840.1.113669.632.20.1211.10000315526/series/1.3.12.2.1107.5.1.4.54693.30000006100507010800000005268/instances/1.3.12.2.1107.5.1.4.54693.30000006100507010800000005466/frames/1 -H 'accept: multipart/related; type=application/octet-stream'
**Documentation**
http://book.orthanc-server.com/plugins/dicomweb.html
> Support for loading frames using WADO-RS (octet-stream)

- package.json
Corrected typo "licnense" in package.json
> Corrected typo "licnense"

- src/imageLoader/wadouri/metaData/metaDataProvider.js
IE11 throws an exception because of this duplicated property.
> wadouri: removing duplicated property

- src/imageLoader/wadouri/metaData/getImagePixelModule.js
This is originally an issue from OHIF: https://github.com/OHIF/Viewers/issues/89
According to DICOM standard, color palette luts should be used only if photometric interpretation is 'PALETTE COLOR'. This fix checks it.
Here is the reference: http://dicom.nema.org/medical/dicom/2014c/output/chtml/part03/sect_C.7.6.3.html
> OHIF #89 Do not use color palette luts if photometric interpretation is not ‘PALETTE COLOR’

- src/imageLoader/internal/xhrRequest.js
'CornerstoneImageLoadStart' when downloading an image starts
'CornerstoneImageLoadEnd' when downloading an image ends
'CornerstoneImageLoadProgress' when downloading an image progresses, even if not lengthComputable (total=undefined and percentComplete=undefined).
'CornerstoneImageLoadProgress' transmits the image url
> more events in xhrRequest

- src/imageLoader/wadors/loadImage.js
Simply browses the content-type for a transfer syntax, and keep ILE as the default.
> Handle the transfer-syntax returned in the response content-type.

- src/imageLoader/decodeImageFrame.js
An Exception is being triggered once the ImageLoader does not find a proper decoder. 
Instead of throwing the exception we are now returning a rejected promise passing the error as a parameter.
> fix(180): Avoid throwing exception for missing transfer syntax decoder

- README.md
- Update README pointing all referencies to dist files to www.unpkg.com instead of rawgit.
> Update README: Project file links from rawgit to unpkg

- config/webpack/webpack-base.js
- examples/customWebWorkerTask/index.html
- examples/utils/customWebWorkersConfig.js
- examples/utils/initializeWebWorkers.js
- Add a config option on webpack in order to fix the issue (based in the solution for this issue https://github.com/webpack/webpack/issues/6677) 
- Adding some verification in the examples config, in case we have dist folder, do not use unpkg files
We need to release a new patch in order to fix the files we were using on unpkg, because the examples rely on them.
> Bugfix189: 'window undefined'

- examples/utils/customWebWorkersConfig.js
- In order to fix an issue on rawgit examples, we need to point directly to rawgit with absolute url, because we are using unpkg webWorkers and both are in different domains.
> Adding a fallback for convolveTask.js between rawgit and locally dev

- codecs/jpeg.js
decoder jpeg lossy bug，Avoid skipping a valid marker
> decoder jpeg lossy bug

- examples/utils/initializeWebWorkers.js
- src/shared/calculateMinMax.js
- test/shared/calculateMinMax_test.js
The method now behaves as follow:
1. If **imageFrame.smallestPixelValue** Or **imageFrame.largestPixelValue** are not defined then we calculate min/max regardless of strict mode.
2. ~~Strict mode is **false** by default. This is so the new configuration is not breaking old implementation.~~
> update calculateMinMax strict mode behavior

- test/decoders_test.js
- test/imageLoader/wadouri/metaDataProvider_test.js
- test/integration_test.js
- test/lossyImagesDecoding_test.js
Increasing integration tests timeout to 5000ms. They are heavy tests so needs more time to run on travisCI.
> Increasing integration tests timeout

- src/imageLoader/internal/xhrRequest.js
Add headers object and parameters to the beforeSend callback to simplify transfer-syntax specification
> feat(options.beforeSend): Add useful things to to beforeSend

- src/imageLoader/wadors/metaData/metaDataProvider.js
- src/imageLoader/wadouri/metaData/metaDataProvider.js
Adds 'overlayPlaneModule' type returning an array of DICOM overlays.
This array is then added the 'overlays' propertry of the image.
This is then read by the overlays tool see - [cornerstonejs/cornerstoneTools#809](https://github.com/cornerstonejs/cornerstoneTools/pull/809)
see issue [cornerstonejs/cornerstoneTools#780](https://github.com/cornerstonejs/cornerstoneTools/issues/780)
see DICOM overlays standard - http://dicom.nema.org/dicom/2013/output/chtml/part03/sect_C.9.html
> DICOM Overlays 

- src/imageLoader/webWorkerManager.js
- src/webWorker/webWorker.js
This PR makes Wado correctly handle decoder errors.
If for example the Jpeg decoder  raises the `'Unsupported color mode'` here https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/master/codecs/jpeg.js#L834
The exception is never caught which means the webworker never sends a failed message to the UI and the UI cannot respond.
The expected behaviour which is fixed with this PR is for decoder exceptions to cause the `EVENTS.IMAGE_LOAD_FAILED` to be sent in the UI
> Handle decoder exceptions

- package.json
- src/imageLoader/internal/xhrRequest.js
- src/imageLoader/wadors/getPixelData.js
- src/imageLoader/wadors/loadImage.js
- src/version.js
Mirrored changes from 2.x for error handling, checked every `then` statement to make sure we are adding a reject call to `onRejection`.
> Check all 'then's and add proper error handling.

- docs/Configuration.md
- src/imageLoader/internal/xhrRequest.js
Allows the user to add an error interceptor so that a user may intercept and process a request error at the app level.
This pattern for a library avoids an application having to try/catch each call across the application, and makes centralizing error management easier.
> Error interceptor

- src/imageLoader/createImage.js
It was currently incorrect for any image not storing data as 1 byte/pixel.
> Update sizeInBytes to the byteLength of the array.

- .eslintrc.js
- package-lock.json
- src/imageLoader/createImage.js
- src/imageLoader/imageIdToURI.js
- src/imageLoader/internal/options.js
- src/imageLoader/wadors/loadImage.js
- src/imageLoader/wadors/metaDataManager.js
- src/shared/decodeImageFrame.js
- src/shared/scaling/scaleArray.js
add convertFloatPixelDataToInt flag (default true)
Pushing to public branch from a private repo. This is used with upcoming Cornerstone volumetric functionality
> fix: improvements for usage of targetBuffer

- README.md
The old unpkg.com paths were wrong. Now they both point to the minimized file and at least work.
> Fix broken unpkg.com paths.

- src/imageLoader/colorSpaceConverters/convertPALETTECOLOR.js
- src/imageLoader/colorSpaceConverters/convertRGBColorByPixel.js
- src/imageLoader/colorSpaceConverters/convertRGBColorByPlane.js
- src/imageLoader/colorSpaceConverters/convertYBRFull422ByPixel.js
- src/imageLoader/colorSpaceConverters/convertYBRFullByPixel.js
- src/imageLoader/colorSpaceConverters/convertYBRFullByPlane.js
- src/imageLoader/convertColorSpace.js
- src/imageLoader/createImage.js
- src/imageLoader/internal/xhrRequest.js
- src/imageLoader/wadors/metaData/metaDataProvider.js
- src/imageLoader/wadouri/metaData/metaDataProvider.js
1. Cornerstone3D does not rely on A in the RGBA, this PR adds the option to not use it. 
2. Adds `transferSyntax` metadata return
> perf: add option to use RGB instead of RGBA

- src/imageLoader/createImage.js
@sedghi @swederik, I was going through to make sure CSWIL would automatically select the proper type for cs3d and think there might be a bug. I could very likely wrong though since afaik no such issue has been reported...
Essentially, cs3d will rely on the native decoded array type CSWIL provides. In the case the PixelData is `PixelRepresentation === 0`, it is usually a `Uint16ArrayBuffer` view for CT data. However, usually this data is preScaled within CSWIL and after scaling, a `Uint16ArrayBuffer` view should really be a `Int16ArrayBuffer`. However, it does not seem like this view is used in the `setPixelDataType` function.
It seems like PixelRepresentation also only refers to the stored pixel data tag, not post slope + intercept. …
> fix: data type view after scaling

- src/imageLoader/wadors/metaData/metaDataProvider.js
Updated the metadata provider adding `(0018,1078) radiopharmaceuticalStartDateTime` to `petIsotopeModule` that is used by [calculate-suv](https://github.com/cornerstonejs/calculate-suv/blob/main/src/calculateStartTime.ts#L30)
> feat(metadata): added radiopharmaceuticalStartDateTime to petIsotopeModule

- src/imageLoader/createImage.js
Properly checks for negative value. @sedghi there is still an edge case if a volume of data has all positive data for a single slice then the Stack Viewport could start with uint16 container then be changed to a int16 container.
Let me know what you think.
> fix: negative checking 16 bit case

- config/webpack/webpack-bundle.js
previously `webpack:bundle` script created `610.bundle.min.js` and `888.bundle.min.js` files that caused incorrect referencing in other applications (examples: [ #511 , #479 , #439 ]).
Updated webpack config to include all chunks together. Actually, this approanch helped with incorrect referencing in embedded OHIF Viewer that we're using in our app
Previous dist build:
Current dist build:
> fix(bundle): include codecs chunks into bundle in bundle mode

- src/shared/scaling/scaleArray.js
Currently PT images that are not in SUV are not rescaled at all. This is problematic because PT images can be in units of e.g. counts or Bq/ml, so it's important that the rescaling is applied in those cases.
cc @sedghi this is the same fix as in https://github.com/cornerstonejs/cornerstone3D-beta/pull/536
> fix(suv display): fix scaling of non-SUV PT images

- src/imageLoader/wadouri/getUncompressedImageFrame.js
Large uncompressed multiframe data will send the full
arraybuffer in a typed view. For large uncompressed data
such as tomo these will result in OOM issues. This fix
pre-slices the typed array view so only used buffer
is sent via worker.postMessage.
> fix: copy buffer to prevent oom in workers
